import asyncio
import os
from dotenv import load_dotenv
from browser_use import Agent, Tools
from browser_use.llm import ChatMistral

# Load environment variables from the .env file
load_dotenv()

async def main():
    # Initialize Mistral using browser-use's optimized native provider wrapper.
    # 'mistral-large-latest' is highly recommended for complex structural reasoning tasks.
    llm = ChatMistral(
        model="mistral-medium-latest",
        api_key=os.getenv("MISTRAL_API_KEY"),
        timeout=90.0,
        max_retries=2,
    )

    tools = Tools(exclude_actions=['search'])

    # Detailed system prompt mapping out both User Flows
    task_prompt = """
    You are an automated QA engineer running E2E tests on https://www.saucedemo.com.
    Execute the following two user flows precisely and verify the results. 
    If a step fails, stop and report the failure.

    USER FLOW 1: Add Product to Cart
    1. Navigate to https://www.saucedemo.com
    2. Log in using credentials: Username is 'standard_user', Password is 'secret_sauce'.
    3. On the Inventory page, find the product 'Sauce Labs Backpack'.
    4. Click on the product name to open the product details page (URL should contain inventory-item.html?id=4).
    5. Click the 'Add to cart' button.
    6. VERIFY: Look at the shopping cart icon in the top-right corner of the current page. 
   Read the number displayed in its badge directly from the page — do not search the web. 
   Confirm it shows '1'.

    USER FLOW 2: Checkout Process (Continue from Flow 1)
    7. Click on the Shopping Cart icon to go to the cart page.
    8. Click on the 'Checkout' button.
    9. On the Checkout Information page, enter these details:
       - First Name: Alla
       - Last Name: Kovalchuk
       - Zip/Postal Code: 0613
    10. Click the 'Continue' button.
    11. Verify you are on the checkout summary page, then click the 'Finish' button.
    12. VERIFY: Confirm that the final page displays the success message 'Thank you for your order!'.

    At the end of the execution, provide a short text summary: 'SUCCESS' if all assertions met, or 'FAILED' with details.
    """

    print("🚀 Starting AI-Driven E2E Test Agent via Native Mistral Engine...")
    
    # Instantiate the agent using our clean Mistral LLM
    agent = Agent(
        task=task_prompt,
        llm=llm,
        tools=tools
    )

    # Run the agent execution loop (this opens Chromium dynamically)
    history = await agent.run()
    
    print("\n🏁 Test Execution Finished!")
    # Print out the final reasoning report and verdict generated by the AI agent
    print(history.final_result())

if __name__ == "__main__":
    asyncio.run(main())